version: 2

updates:
  # node.js modules
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: Dependencies"
    assignees:
      - "RShirohara"
    reviewers:
      - "RShirohara"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: CI"
      - "Type: Dependencies"
    assignees:
      - "RShirohara"
    reviewers:
      - "RShirohara"
